<a href="https://colab.research.google.com/github/dhanushbt/AI_ML_BASICS/blob/test_branch/Eigen_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
a

array([[ 2, -2,  3],
       [ 1,  1,  1],
       [ 1,  3, -1]])

Eigen value and vectors

> Add blockquote



In [3]:
values,vector=np.linalg.eig(a)
print("value:",values)
print("vector:",vector)

value: [ 3.  1. -2.]
vector: [[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [5]:
b=np.array([[2,0,0],[0,1,0],[0,0,3]])

In [6]:
values1,vector1=np.linalg.eig(b)
print("value:",values1)
print("vector:",vector1)

value: [2. 1. 3.]
vector: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
