<a href="https://colab.research.google.com/github/dhanushbt/AI_ML_BASICS/blob/test_branch/Matrix_implementation_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix implementation

In [1]:
import numpy as np

In [31]:
p=np.array([[1,2,3],[4,5,6]])
q=np.array([[1,2],[3,4],[5,6]])
r=np.array([[1,0,1],[2,0,1]])
a=np.array([[1,9,3],[4,5,6],[7,8,9]])

Matrix addition

In [9]:
s=np.add(p,r)
print(s)


[[2 2 4]
 [6 5 7]]


Matrix substraction

In [16]:
t=np.subtract(p,r)
print(t)

[[0 2 2]
 [2 5 5]]


matrix multiplication

In [26]:
d=np.linalg.multi_dot([p,q])
print(d)

[[22 28]
 [49 64]]


Note for 1d array it does dot product of vector
But for 2d array it does matrix multiplication




In [23]:
d=p @ q
print(d)

[[22 28]
 [49 64]]


Determinant of Matrix

In [32]:
det=np.linalg.det(a)
print(det)

42.00000000000001


inverse of matrix

In [33]:
inv=np.linalg.inv(a)
print(inv)

[[-0.07142857 -1.35714286  0.92857143]
 [ 0.14285714 -0.28571429  0.14285714]
 [-0.07142857  1.30952381 -0.73809524]]


Transpose

In [37]:
trpose=np.linalg.matrix_transpose(p)
print(trpose)

[[1 4]
 [2 5]
 [3 6]]
