<a href="https://colab.research.google.com/github/dhanushbt/AI_ML_BASICS/blob/test_branch/SVDpt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [3]:
a=np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])

In [4]:
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0]])

Finding SVD should look like

**[3 * 3] [diagonal values][ 4 * 4]**
rank is 3 so atmost 3 diagonal values


In [5]:
u,v,s=np.linalg.svd(a,full_matrices=True)

In [11]:
v

array([6.7509, 1.1734, 0.2186])

In [9]:
u.dot(u.T)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

create diagonal matrix

In [17]:
sd=np.diag(v)

In [19]:
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.2186]])

In [20]:
b=np.zeros((3,4))

In [21]:
b[:,:-1]=sd

In [22]:
b

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])

In [23]:
sigma=b

In [24]:
print(np.dot(np.dot(u,sigma),s))

[[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [ 0.  1.  1. -0.]]


now we will do 2 rank approximation

In [25]:
v=[6.7509, 1.1734, 0]

In [26]:
sd=np.diag(v)

In [28]:
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.    ]])

In [29]:
b=np.zeros((3,4))

In [30]:
b[:,:-1]=sd

In [31]:
sigma=b
print(np.dot(np.dot(u,sigma),s))

[[ 1.0959  1.9567  3.0526  3.9542]
 [ 0.8764  1.0558  1.9322  3.0589]
 [-0.0559  1.0252  0.9693  0.0267]]


In [32]:
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]
